// Enterprise Workflow States definition
export const WORKFLOW_STATES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  RECOMMENDED: 'RECOMMENDED',
  APPROVED: 'APPROVED',
  IMPLEMENTED: 'IMPLEMENTED',
  REJECTED: 'REJECTED'
};

export const WORKFLOW_TRANSITIONS = {
  [WORKFLOW_STATES.DRAFT]: [WORKFLOW_STATES.SUBMITTED],
  [WORKFLOW_STATES.SUBMITTED]: [WORKFLOW_STATES.RECOMMENDED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.RECOMMENDED]: [WORKFLOW_STATES.APPROVED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.APPROVED]: [WORKFLOW_STATES.IMPLEMENTED, WORKFLOW_STATES.REJECTED],
  [WORKFLOW_STATES.IMPLEMENTED]: [],
  [WORKFLOW_STATES.REJECTED]: [WORKFLOW_STATES.DRAFT] // Allows resubmission depending on rules
};

// UI Styling mapping for Status Badges
export const STATE_STYLES = {
  [WORKFLOW_STATES.DRAFT]: 'bg-gray-100 text-gray-800',
  [WORKFLOW_STATES.SUBMITTED]: 'bg-blue-100 text-blue-800',
  [WORKFLOW_STATES.RECOMMENDED]: 'bg-purple-100 text-purple-800',
  [WORKFLOW_STATES.APPROVED]: 'bg-green-100 text-green-800',
  [WORKFLOW_STATES.IMPLEMENTED]: 'bg-teal-100 text-teal-800',
  [WORKFLOW_STATES.REJECTED]: 'bg-red-100 text-red-800'
};
